CREATE TABLE IF NOT EXISTS endpoint_hit
(
    hit_id    INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app       VARCHAR(150) NOT NULL,
    uri       VARCHAR(150),
    ip        VARCHAR(30),
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT endpoint_hit_id_pk PRIMARY KEY (hit_id)
);